services:
  
  streamlit_ui:
    build: ./docker/ui
    env_file:
      - .env
    ports: ["8501:8501"]

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --cleanup

volumes:
  data:
